base_url = "https://example.com"
compile_sass = false
build_search_index = false

title = "Title"
description = "description"
generate_feeds = true
feed_filenames = ["atom.xml"]
default_language = "zh_CN"

taxonomies = [
    {name = "tags", feed = true}
]

[markdown.highlighting]
light_theme = "material-theme-lighter"
dark_theme = "material-theme-palenight"

[extra]
menu = [
    {url = "$BASE_URL/about", name = "About"}
]
copyright = "All right reserved"
