base_url = "https://chenx6.github.io/"
compile_sass = false
build_search_index = false

title = "二进制咸鱼的自我救赎"
description = "幸福往往是摸的透彻，而敬业的心却常常隐藏。"
generate_feed = true
feed_filename = "atom.xml"
default_language = "zh_CN"

taxonomies = [
    {name = "tags", feed = true}
]

[markdown]
highlight_code = true

highlight_theme = "css"
highlight_themes_css = [
  { theme = "ayu-dark", filename = "syntax-theme-dark.css" },
  { theme = "ayu-light", filename = "syntax-theme-light.css" },
]

[extra]
menu = [
    {url = "$BASE_URL/about", name = "About"}
]
